### ISSUE TITLE
Is there a way to check if next token is END?

### ISSUE THREAD

**Issue by danvim** [atorstling/bychan#37]
I just checked out the minilang example and read through the code. When I saw the `StatementNode`, I was struggling to find a way to add an ending semicolon for conventional purpose. In your example, the `;` is used to separate statements, but there isn't a way to end a script with the last statement ending with a `;` because the parser isn't able to parse the end and would result in:

    'Premature end reached' @  position ..., current lexeme is END ...

Is there a way to check whether the next token is the `END` or is what I'm thinking incorrect and looking ahead isn't the right thing to do and that there are other ways?

**Comment by atorstling** [comment]
Try `parser.nextIs(EndToken.get())`. The end token is unparseable by design and is used by LexParser to assure that the entire input is consumed when calling parseFully. If you are writing statements and not expressions, you will most likely want to do this

**Comment by atorstling** [comment]
In the minilang example, the semicolon is simply a separator between sub-expressions, and the whole language is expression based. If you use this approach, you won't need to check for an end token. This is due to the fact that the end token has LBP 0. When you parse the whole expression using LexParser, it will continue until it finds a token with LBP <=0.  If you call parseFully it will also check that only the end token remains as i mentioned above.

**Comment by danvim** [comment]
@atorstling "The end token is unparseable by design" I thought I read that part correctly. When I do `parser.nextIs(EndToken.get())`, the IDE simply says `no instance(s) of type variable(s) N exist so that EndToken<N> conforms to TokenKey` I'm sorry, I may not be that advance in Java to figure out a solution. :(

**Comment by atorstling** [comment]
Ah, my bad, let me get back to you when I'm at a computer.

**Comment by danvim** [comment]
http://stackoverflow.com/questions/40949670/is-there-a-way-to-check-if-next-token-is-end

**Comment by atorstling** [comment]
Thanks. That was an omission, see the stackoverflow post. Fix applied.

**Comment by atorstling** [comment]
Hey @danvim, I don't know how to reach you, do you have gitter? Anyway, I decided to clean up a lot of cruft in Bychan, and broke backwards compatibility while doing it. Basically as the end of the README says, the support for statements was not that great. The Repl and LexParser more or less assumed that you would always start by parsing an expression. I've changed that assumption now and made the API against the Parser identical irrespective if you are parsing from a token callback or not. So you are now able to move code out of token callbacks into functions and call functions in a recursive descend fashion. Check ReadmeExamples::statements for an example. I hope this makes it easier for you to parse statements, certainly if your topmost production is a statement.

**Comment by danvim** [comment]
@atorstling Thanks, I'll check that out very soon. :)
